RegisterNetEvent('Radio:CallData')
AddEventHandler('Radio:CallData', function()
  local DataUser = exports.platypus:GetDataPlayers()
  TriggerClientEvent("Radio:CallData:cb", source, DataUser[source])
end)
