
function OpenMenuInteraction()
	TriggerEvent('Menu:Init', "Interactions", "option", '#FF171799',
		"http://www.socialmediaimpact.com/wp-content/uploads/2013/08/social-interaction-graphic-cropped.jpg")
	Menu.setTitle("Interactions")
	Menu.setSubtitle("option")
	Menu.clearMenu()
	Menu.addButton2("Emote", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Enlever/Mettre masque", "toggleMask", nil, nil, nil)
	Menu.addButton2("Inventaire (K)", "extOpenInventory", nil, nil, nil)
	Menu.addButton2("Coffre véhicule (L)", "extOpenCoffreVeh", nil, nil, nil)
	Menu.addButton2("Téléphone (F2)", "extOpenTel", nil, nil, nil)
	Menu.addButton2("Changer la distance vocal (F6)", "extSwitDistance", nil, nil, nil)
	Menu.addButton2("S'évanouir (ALT+G)", "DoRagdoll", nil, nil, nil)
	Menu.addButton2("Masquer l'HUD", "maskHUD", nil, nil, nil)
	--Menu.addButton2("Action", func, nil, nil, nil)
	--Menu.addButton2("Mes accessoires", func, args, hover, picture)
	Menu.addButton2("Se suicider", "killYourSelf", nil, nil, nil)
	Menu.CreateMenu()
end

function OpenAnimation()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenMenuInteraction", nil, nil, nil)
	Menu.addButton2("Annuler Animation", "ClearAnim", nil, nil, nil)
	Menu.addButton2("Saluer", "AnimSaluer", nil, nil, nil)
	Menu.addButton2("Humeur", "AnimHumeur", nil, nil, nil)
	Menu.addButton2("Sportives", "AnimSportives", nil, nil, nil)
	Menu.addButton2("Festives", "AnimFestives", nil, nil, nil)
	Menu.addButton2("Prendre une pose", "AnimPose", nil, nil, nil)
	Menu.addButton2("Autres", "AnimAutres", nil, nil, nil)
	Menu.addButton2("Metier", "AnimMetier", nil, nil, nil)
	Menu.addButton2("Retour", "OpenMenuInteraction", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimSaluer()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Serrer la main", "playAnim", {"mp_common",'givetake1_a'}, nil, nil)
	Menu.addButton2("Dire bonjour", "playAnim", {"gestures@m@standing@casual",'gesture_hello'}, nil, nil)
	Menu.addButton2("Tchek", "playAnim", {"mp_ped_interaction",'handshake_guy_a'}, nil, nil)
	Menu.addButton2("Signe de la main", "playAnim", {"friends@frj@ig_1",'wave_e'}, nil, nil)
	Menu.addButton2("Salut militaire", "playAnim", {"mp_player_int_uppersalute",'mp_player_int_salute'}, nil, nil)
	Menu.addButton2("Salut bandit", "playAnim", {"mp_ped_interaction",'hugs_guy_a'}, nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimHumeur()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Craquer poings (f)", "playAnim", {"anim@mp_player_intcelebrationfemale@knuckle_crunch",'knuckle_crunch'}, nil, nil)
	Menu.addButton2("Craquer poings (h)", "playAnim", {"anim@mp_player_intcelebrationmale@knuckle_crunch",'knuckle_crunch'}, nil, nil)
	Menu.addButton2("Branleur", "playAnim", {"mp_player_int_upperwank",'mp_player_int_wank_01'}, nil, nil)
	Menu.addButton2("Dammed", "playAnim", {"gestures@m@standing@casual",'gesture_damn'}, nil, nil)
	Menu.addButton2("Calme toi", "playAnim", {"gestures@m@standing@casual",'gesture_easy_now'}, nil, nil)
	Menu.addButton2("No way", "playAnim", {"gestures@m@standing@casual",'gesture_no_way'}, nil, nil)
	Menu.addButton2("Doigt d'honneur", "playAnim", {"mp_player_int_upperfinger",'mp_player_int_finger_01_enter'}, nil, nil)
	Menu.addButton2("Faire un doigt", "playAnim", {"mp_player_intfinger",'mp_player_int_finger'}, nil, nil)
	Menu.addButton2("Balle dans la tete", "playAnim", {"mp_suicide",'pistol'}, nil, nil)
	Menu.addButton2("Enlacer", "playAnim", {"mp_ped_interaction",'kisses_guy_a'}, nil, nil)
	Menu.addButton2("Toi", "playAnim", {"gestures@m@standing@casual",'gesture_point'}, nil, nil)
	Menu.addButton2("Keskya ?", "playAnim", {"gestures@m@standing@casual",'gesture_bring_it_on'}, nil, nil)
	Menu.addButton2("A moi", "playAnim", {"gestures@m@standing@casual",'gesture_me'}, nil, nil)
	Menu.addButton2("Je le savais, putain", "playAnim", {"anim@am_hold_up@male",'shoplift_high'}, nil, nil)
	Menu.addButton2("Etre épuisé", "playAnim", {"amb@world_human_jog_standing@male@idle_b",'idle_d'}, nil, nil)
	Menu.addButton2("Je suis dans la merde", "playAnim", {"friends@frj@ig_1",'wave_e'}, nil, nil)
	Menu.addButton2("Facepalm", "playAnim", {"anim@mp_player_intcelebrationmale@face_palm",'face_palm'}, nil, nil)
	Menu.addButton2("Qu'est ce que j'ai fait ?", "playAnim", {"oddjobs@assassinate@multi@",'react_big_variations_a'}, nil, nil)
	Menu.addButton2("Avoir peur", "playAnim", {"amb@code_human_cower_stand@male@react_cowering",'base_right'}, nil, nil)
	Menu.addButton2("Fight ?", "playAnim", {"anim@deathmatch_intros@unarmed",'intro_male_unarmed_e'}, nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimSportives()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Faire du Yoga", "playEmote", "WORLD_HUMAN_YOGA", nil, nil)
	Menu.addButton2("Jogging", "playEmote", "WORLD_HUMAN_JOG_STANDING", nil, nil)
	Menu.addButton2("Faire des pompes", "playEmote", "WORLD_HUMAN_PUSH_UPS", nil, nil)
	Menu.addButton2("Faire des abdos", "playEmote", "WORLD_HUMAN_SIT_UPS", nil, nil)
	Menu.addButton2("Bodybuilder", "playEmote", "WORLD_HUMAN_MUSCLE_FLEX", nil, nil)
	Menu.addButton2("Soulever poids", "playEmote", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimFestives()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Danse Femme", "playAnim", {"mini@strip_club@private_dance@part1",'priv_dance_p1'}, nil, nil)
	Menu.addButton2("LapDanse Femme", "playAnim", {"mp_am_stripper",'lap_dance_girl'}, nil, nil)
	Menu.addButton2("Danser", "playAnim", {"amb@world_human_partying@female@partying_beer@base",'base'}, nil, nil)
	Menu.addButton2("Danse gangsta", "playAnim", {"missfbi3_sniping",'dance_m_default'}, nil, nil)
	Menu.addButton2("Tappes moi en 5", "playAnim", {"mp_ped_interaction",'highfive_guy_a'}, nil, nil)
	Menu.addButton2("Boire une biere", "playEmote", "WORLD_HUMAN_DRINKING", nil, nil)
	Menu.addButton2("Bière en zik", "playEmote", "WORLD_HUMAN_PARTYING", nil, nil)
	Menu.addButton2("Jouer de la musique", "playEmote", "WORLD_HUMAN_MUSICIAN", nil, nil)
	Menu.addButton2("Applaudir", "playEmote", "WORLD_HUMAN_CHEERING", nil, nil)
	Menu.addButton2("Super", "playAnim", {"mp_action",'thanks_male_06'}, nil, nil)
	Menu.addButton2("Excelent", "playAnim", {"anim@mp_player_intcelebrationmale@thumbs_up",'thumbs_up'}, nil, nil)
	Menu.addButton2("Dj", "playAnim", {"anim@mp_player_intcelebrationmale@dj",'dj'}, nil, nil)
	Menu.addButton2("Air Guitar", "playAnim", {"anim@mp_player_intcelebrationmale@air_guitar",'air_guitar'}, nil, nil)
	Menu.addButton2("Air Shagging", "playAnim", {"anim@mp_player_intcelebrationfemale@air_shagging",'air_shagging'}, nil, nil)
	Menu.addButton2("Rock and Roll", "playAnim", {"mp_player_int_upperrock",'mp_player_int_rock'}, nil, nil)
	Menu.addButton2("Bourré sur place", "playAnim", {"amb@world_human_bum_standing@drunk@idle_a",'idle_a'}, nil, nil)
	Menu.addButton2("Vomir en voiture", "playAnim", {"oddjobs@taxi@tie",'vomit_outside'}, nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimPose()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Pose de la police", "playEmote", "WORLD_HUMAN_COP_IDLES", nil, nil)
	Menu.addButton2("Accouder au comptoir", "playEmote", 'PROP_HUMAN_BUM_SHOPPING_CART', nil, nil)
	--Menu.addButton2("S'assoir", "playAnim", {"amb@world_human_partying@female@partying_beer@base",'base'}, nil, nil)
	Menu.addButton2("Assis au sol", "playEmote", "WORLD_HUMAN_PICNIC", nil, nil)
	Menu.addButton2("Attendre contre un mur", "playEmote", "world_human_leaning", nil, nil)
	Menu.addButton2("Sur le ventre", "playEmote", "WORLD_HUMAN_SUNBATHE", nil, nil)
	Menu.addButton2("Sur le dos", "playEmote", "WORLD_HUMAN_SUNBATHE_BACK", nil, nil)
	Menu.addButton2("Nettoyer quelque chose", "playEmote", "world_human_maid_clean", nil, nil)
	Menu.addButton2("Préparer à manger", "playEmote", "PROP_HUMAN_BBQ", nil, nil)
	Menu.addButton2("Ecouter à une porte", "playAnim", {"mini@safe_cracking",'idle_base'}, nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimAutres()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Oui", "playAnim", {"gestures@m@standing@casual",'gesture_pleased'}, nil, nil)
	Menu.addButton2("Non", "playAnim", {"gestures@m@standing@casual",'gesture_head_no'}, nil, nil)
	Menu.addButton2("Donner", "playAnim", {"gestures@m@standing@casual",'gesture_head_no'}, nil, nil)
	Menu.addButton2("Pose michto", "playEmote", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", nil, nil)
	Menu.addButton2("Prendre des notes", "playEmote", "WORLD_HUMAN_CLIPBOARD", nil, nil)
	Menu.addButton2("Fumer un joint", "playEmote", "WORLD_HUMAN_SMOKING_POT", nil, nil)
	Menu.addButton2("Se gratter les c**", "playAnim", {"gestures@m@standing@casual",'gesture_no_way'}, nil, nil)
	Menu.addButton2("Selfie", "playEmote", "WORLD_HUMAN_TOURIST_MOBILE", nil, nil)
	Menu.addButton2("Portable", "playEmote", "WORLD_HUMAN_STAND_MOBILE", nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end

function AnimMetier()
	Menu.setSubtitle("Emote")
	Menu.clearMenu()
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.addButton2("Police : jumelles", "playEmote", "WORLD_HUMAN_BINOCULARS", nil, nil)
	Menu.addButton2("Police : circulation", "playEmote", "WORLD_HUMAN_CAR_PARK_ATTENDANT", nil, nil)
	Menu.addButton2("Dépanneur : réparer le moteur", "playAnim", {"mini@repair",'fixing_a_ped'}, nil, nil)
	Menu.addButton2("Médecin : observer", "playEmote", "CODE_HUMAN_MEDIC_KNEEL", nil, nil)
	Menu.addButton2("Taxi : parler au client", "playAnim", {"oddjobs@taxi@driver",'leanover_idle'}, nil, nil)
	Menu.addButton2("Taxi : donner la facture", "playAnim", {"oddjobs@taxi@cyi",'std_hand_off_ps_passenger'}, nil, nil)
	Menu.addButton2("Epicier : donner les courses", "playAnim", {"mp_am_hold_up",'purchase_beerbox_shopkeeper'}, nil, nil)
	Menu.addButton2("Barman : servir un shot", "playAnim", {"mini@drinking",'shots_barman_b'}, nil, nil)
	Menu.addButton2("Journaliste : Prendre une photo", "playEmote", "WORLD_HUMAN_PAPARAZZI", nil, nil)
	Menu.addButton2("Tout métiers : Coup de marteau", "playEmote", "WORLD_HUMAN_HAMMERING", nil, nil)
	Menu.addButton2("Clochard : Faire la statue", "playEmote", "WORLD_HUMAN_HUMAN_STATUE", nil, nil)
	Menu.addButton2("Clochard : Faire la manche", "playEmote", "WORLD_HUMAN_BUM_FREEWAY", nil, nil)
	Menu.addButton2("Souffleur", "playEmote", "WORLD_HUMAN_GARDENER_LEAF_BLOWER", nil, nil)
	Menu.addButton2("Agriculture : récolter", "playEmote", "WORLD_HUMAN_GARDENER_PLANT", nil, nil)
	Menu.addButton2("Peche", "playEmote", "WORLD_HUMAN_STAND_FISHING", nil, nil)
	Menu.addButton2("Soudure", "playEmote", "WORLD_HUMAN_WELDING", nil, nil)
	Menu.addButton2("Examiner corp", "playEmote", "CODE_HUMAN_MEDIC_TEND_TO_DEAD", nil, nil)
	Menu.addButton2("Verbaliser", "playEmote", "CODE_HUMAN_MEDIC_TIME_OF_DEATH", nil, nil)
	Menu.addButton2("Marteau piqueur", "playEmote", "WORLD_HUMAN_CONST_DRILL", nil, nil)
	Menu.addButton2("Suspect : se rendre à la police", "playAnim", {"random@arrests@busted",'idle_c'}, nil, nil)
	Menu.addButton2("Retour", "OpenAnimation", nil, nil, nil)
	Menu.CreateMenu()
end
