resource_manifest_version "05cfa83c-a124-4cfa-a768-c24a5811d8f9"

 ui_page "/hud/html/index.html"

client_script {
	"/debug/client.lua",
	"/client/menu.lua",
	"/client/blips.lua",
	"/client/function.lua",
	"/client/sirenControl.js",
	"/client/teleport.lua",
	"/inventory/client.lua",
	"/bank/config.lua",
	"/bank/client.lua",
	"/carShop/config.lua",
	"/carShop/client.lua",
	"/garage/client.lua",
	"/garage/table.lua",
	"/life/client.lua"
}
server_script {
	"@mysql-async/lib/MySQL.lua",
	"/server/login.lua",
	"/server/function.lua",
	"/inventory/server.lua",
	"/bank/server.lua",
	"/carShop/server.lua",
	"/garage/server.lua",
	"/life/server.lua"
}

files {
	"/html/assets/images/fleeca.png",
	"/html/assets/images/blaine.png",
	"/html/assets/images/pacific.png",
	"/html/assets/images/background.png",
	"/html/assets/images/button.png",
	"/html/assets/images/button_active.png",
	"/html/assets/images/button_cancel.png",
	"/html/assets/images/button_cancel_active.png",
	"/html/assets/images/button_done.png",
	"/html/assets/images/button_done_active.png",
	"/html/assets/images/button_wrong.png",
	"/html/assets/images/button_wrong_active.png",
	"/html/assets/images/card.png",
	"/html/assets/images/cardflash.gif",
	"/html/assets/images/code_background.png",
	"/html/assets/images/error.png",
	"/html/assets/images/loading.png",
	"/html/assets/images/logo.png",
	"/html/assets/images/money.gif",
	"/html/assets/images/receipt.gif",
	"/html/assets/images/welcome.png",
	"/html/assets/images/welcome_code.png",
	"/html/assets/images/cheque.png",
	"/html/assets/images/carteidentite.png",
	"/html/assets/images/permis.png",
	"/html/assets/images/visa.png",
	"/html/assets/images/femme.jpg",
	"/html/assets/images/homme.jpg",
	"/html/assets/sounds/click.ogg",
	"/html/assets/sounds/insert.ogg",
	"/html/assets/sounds/money.ogg",
	"/html/assets/sounds/error.ogg",
	"/html/assets/fonts/roboto/Roboto-Bold.woff",
	"/html/assets/fonts/roboto/Roboto-Bold.woff2",
	"/html/assets/fonts/roboto/Roboto-Light.woff",
	"/html/assets/fonts/roboto/Roboto-Light.woff2",
	"/html/assets/fonts/roboto/Roboto-Medium.woff",
	"/html/assets/fonts/roboto/Roboto-Medium.woff2",
	"/html/assets/fonts/roboto/Roboto-Regular.woff",
	"/html/assets/fonts/roboto/Roboto-Regular.woff2",
	"/html/assets/fonts/roboto/Roboto-Thin.woff",
	"/html/assets/fonts/roboto/Roboto-Thin.woff2",
	"/html/assets/css/materialize.min.css",
	"/html/assets/css/style.css",
	"/html/assets/css/bank.css",
	"/html/assets/css/identity.css",
	"/html/assets/css/cheque.css",
	"/html/assets/js/jquery.js",
	"/html/assets/js/materialize.js",
	"/html/assets/js/init.js",
	"/html/assets/js/bank.js",
	"/html/assets/js/identity.js",
	"/html/assets/js/cheque.js",
	"/html/index.html",
	"/html/bank.html",
	"/html/identity.html",
	"/hud/html/index.html",
	"/hud/html/scss/hud.css",
	"/hud/html/hud.js",
	"/html/cheque.html"
}

export "GetBlacklistedList"
export "GetBalancedList"
export "GetBalancedCatList"
